services:
  - type: web
    name: yasmin-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000